/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: ['./src/**/*.{html,ts}'],
  theme: {
    extend: {
      colors: {
        primary: '#000666',
        'primary-container': '#1a237e',
        'primary-fixed': '#e0e0ff',
        'primary-fixed-dim': '#bdc2ff',
        'on-primary': '#ffffff',
        'on-primary-fixed': '#000767',
        'on-primary-fixed-variant': '#343d96',
        secondary: '#1b6d24',
        'secondary-container': '#a0f399',
        'on-secondary': '#ffffff',
        'on-secondary-container': '#217128',
        tertiary: '#251900',
        'tertiary-container': '#3f2d00',
        'on-tertiary': '#ffffff',
        'on-tertiary-container': '#c19000',
        surface: '#f9f9fb',
        background: '#f9f9fb',
        'surface-bright': '#f9f9fb',
        'surface-dim': '#d9dadc',
        'surface-tint': '#4c56af',
        'surface-variant': '#e2e2e4',
        'surface-container': '#eeeef0',
        'surface-container-low': '#f3f3f5',
        'surface-container-lowest': '#ffffff',
        'surface-container-high': '#e8e8ea',
        'surface-container-highest': '#e2e2e4',
        'on-surface': '#1a1c1d',
        'on-surface-variant': '#454652',
        'on-background': '#1a1c1d',
        'inverse-surface': '#2f3132',
        'inverse-on-surface': '#f0f0f2',
        'inverse-primary': '#bdc2ff',
        outline: '#767683',
        'outline-variant': '#c6c5d4',
        error: '#ba1a1a',
        'error-container': '#ffdad6',
        'on-error': '#ffffff',
        'on-error-container': '#93000a',
      },
      fontFamily: {
        headline: ['Manrope', 'sans-serif'],
        display: ['Manrope', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
        wordmark: ['Outfit', 'Manrope', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
      },
    },
  },
  plugins: [require('@tailwindcss/forms')],
};
